### ISSUE TITLE
SmelterMiner crash/error once base grows substantially

### ISSUE THREAD

**Issue by rmwoj** [jinxOAO/DSPmods_BepInEx#9]
Hello! First, amazing job with all the mods. Very impressive work.

Once my base grows to endgame levels (1800+ Universe Science/min), the SmelterMiner mod causes an error. Would you mind looking into this? Thanks in advance! 

![image](https://user-images.githubusercontent.com/35611671/109669252-ef20ea80-7b3f-11eb-9ab0-b70985f6fd1c.png)

**Comment by jinxOAO** [comment]
Your problem helps a lot. I‘ve already received some feedback about errors, but I cannot locate the problem. Your screenshot helped me find it. In the newer version, this should be fixed. Please download the latest version of the mod and try it. If it still causes an error, please tell me.  Thanks again.

**Comment by rmwoj** [comment]
Hey, awesome work with the turnaround time! Very impressive. I updated to v1.2 and unfortunately still get the error: 

![image](https://user-images.githubusercontent.com/35611671/109677624-d9172800-7b47-11eb-86b2-fff0e720a67e.png)

How can I help you more?

**Comment by jinxOAO** [comment]
Might need a little more time now:(
Is it possible for you to upload your game save file( with errors and before errors?)

**Comment by rmwoj** [comment]
No worries. Take your time! I'm sure you can figure this out you seem brilliant.

I'm trying to get my game save file to <10MB to upload here but I can't seem to get it under 60MB. Let me delete my sphere and see if that helps. One moment.

**Comment by jinxOAO** [comment]
https://github.com/jinxOAO/DSPTestDll/releases/tag/1.2.1
would you like to try this again(download the dll and replace the old version)? If you find there is no more errors but the miners would work in a wrong way(such as not produce the glass but stone) please tell me.

**Comment by djemrelek** [comment]
ı am getting same problem for 5th time

**Comment by djemrelek** [comment]
A coal smelter miner causing the problem and when ı deconstruct that miner game continuous

**Comment by jinxOAO** [comment]
Sorry again. This is my fault cause I didn't test 

> A coal smelter miner causing the problem and when ı deconstruct that miner game continuous

Got that. Is this version still not fixing that? https://github.com/jinxOAO/DSPTestDll/releases/tag/1.2.1
If it is not, will this helps? https://github.com/jinxOAO/DSPTestDll/releases/tag/1.2.2

**Comment by djemrelek** [comment]
ı was using mod manager to update mods, how can ı install the .dll

**Comment by jinxOAO** [comment]
Rename it to SmelterMiner.dll, drag this into the Dyson Sphere “Program/BepInex/plugins” and replace the original SmelterMiner.dll with the new version.

**Comment by rmwoj** [comment]
I just tested 1.2.1. Outputs are smelted components as before, but the error still comes up. I'll try 1.2.2 now.

**Comment by jinxOAO** [comment]
Did you upgrade the dll and then, load the save file which is already had the errors before you saved?

**Comment by djemrelek** [comment]
ı am still looking for game folder location lol

**Comment by rmwoj** [comment]
My save file I'm testing is ~2 mins before the error comes up.  If you have a way to share 60MB of data I would be happy to share it with you.

**Comment by jinxOAO** [comment]
And remeber to exit the whole game before you update the mod.
For sharing the save file,maybe try google dive?

**Comment by rmwoj** [comment]
Yep, full exit before each test. 

1.2.2 did not fix the error :(

I'm uploading to google drive now one moment please.

**Comment by rmwoj** [comment]
https://drive.google.com/file/d/1d08r_HhjlBF0nbsZZrUB53TlA4I3t6_D/view?usp=sharing

Restricted it to permission only. Hope that's okay I just don't want people snooping around in my drive.

**Comment by rmwoj** [comment]
@djemrelek if you're using r2modman the file location is ...\Roaming\r2modmanPlus-local\DysonSphereProgram\mods\cache\jinxOAO-SmelterMiner

**Comment by jinxOAO** [comment]
thx, I'm trying, This may take a while.....

**Comment by djemrelek** [comment]
oh thanks ı was wonderin how can ı open the save file without other mods, because game cant even open

**Comment by rmwoj** [comment]
@jinxOAO No need to rush! Good luck and please let me know if I can provide any other help.

**Comment by jinxOAO** [comment]
Thank you for your help and tolerance. I will try my best to fix this problem.

**Comment by jinxOAO** [comment]
What other mods are you using?

**Comment by djemrelek** [comment]
ı tested it out with 1.2.2 and same problem again if you want ı can upload my save
ı know the exact mine that cause the problem but ı am using 20 other mod with r2modman

**Comment by rmwoj** [comment]
Absolutely.

My full mod list:
BepInEx
CopyInserters
LDBTool
More_Smelters
StarmapBuffs
No_Advisor
NoAutoZoomIn
MoreOrLessDense
More_or_Less_Stars
FreeFoundations
AdvancedBuildDestruct
PowerNodeMultipliers
EnergyManager_Generators
SuperOrbitalCollectors
DspGameSpeed
MegaSystems
Star_Map_Tools
SphereSaveFix
SuperNightLight
Denseiverse
SmartTank
SuperBelt
SmelterMiner

**Comment by djemrelek** [comment]
https://drive.google.com/drive/folders/19KXlDYvACf9GXh2TMCwSFJJ1RRdEPAOe?usp=sharing

**Comment by jinxOAO** [comment]
I've upload 1.3.0. I hope it works. I've tried this on rmwoj's save (I can't load djemrelek's save, sry), and for about 5min with 3x speed, it didn't show any errors, and the console prints something that I expected. So I think it might works this time.
Since it's 4 am in the morning, I have to go to bed, so your reply may not be seen until a long time later. If there are still problems (hope not), I will try my best to continue trying to fix.
Nice factorys btw.
sincere thanks for you two , and, Good luck (for myself, too XD)

**Comment by jinxOAO** [comment]
The errors occured because "the miner(with recipe 2 ore -> 1 product) finished mining the whole mineral veins". That's what I found, based on your saves and descriptions.

**Comment by rmwoj** [comment]
AMAZING! I'm thoroughly impressed with your passion my friend. Hats off to you. 

I'm letting my save run now at 3x to verify. All looks good so far. I'll let it run for a few hours and let you know if anything else comes up.

A huge pat on the back for you my friend.

**Comment by djemrelek** [comment]
> The errors occured because "the miner(with recipe 2 ore -> 1 product) finished mining the whole mineral veins". That's what I found, based on your saves and descriptions.

yea when there is 1 ore but it has to be 2 ore to produce 1, it cant find any ore thats why ı have "-3 iron ore vein" in my base

**Comment by djemrelek** [comment]
ı am gonna test it tomorrow too ı have to go bed thanks for your work and help

**Comment by rmwoj** [comment]
I just tested for the last 3 hours on 3x speed. No issues.

You got it man congratulations! Closing this issue now.
